name: Deploy to GitHub Pages

# Запускаем магию только на пуши в main
on:
  push:
    branches: master
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish Fancy.Blazor/Fancy.Blazor.csproj -c Release --output release --nologo

    # changes the base-tag in index.html from '/' to 'Fancy' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to Fancy
      run: sed -i 's/<base href="\/" \/>/<base href="\/Fancy\/" \/>/g' release/wwwroot/index.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
